<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N_R38TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N.r_38T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N.r_38T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'med' => ['privates', '.errored..service_locator.N.r_38T.App\\Entity\\Meds', NULL, 'Cannot autowire service ".service_locator.N.r_38T": it references class "App\\Entity\\Meds" but no such service exists.'],
        ], [
            'med' => 'App\\Entity\\Meds',
        ]);
    }
}
