<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WHLSBORService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wHLSBOR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wHLSBOR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rep' => ['privates', 'App\\Repository\\DiagnosticRequestRepository', 'getDiagnosticRequestRepositoryService', true],
        ], [
            'rep' => 'App\\Repository\\DiagnosticRequestRepository',
        ]);
    }
}
