<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O1QAtw_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O1QAtw.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O1QAtw.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'medsrepository' => ['privates', 'App\\Repository\\MedsRepository', 'getMedsRepositoryService', true],
            'prescriptionRepository' => ['privates', 'App\\Repository\\PrescriptionRepository', 'getPrescriptionRepositoryService', true],
        ], [
            'entityManager' => '?',
            'medsrepository' => 'App\\Repository\\MedsRepository',
            'prescriptionRepository' => 'App\\Repository\\PrescriptionRepository',
        ]);
    }
}
