<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZPdZQHsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZPdZQHs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZPdZQHs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'medicalRecord' => ['privates', '.errored..service_locator.ZPdZQHs.App\\Entity\\MedicalRecord', NULL, 'Cannot autowire service ".service_locator.ZPdZQHs": it references class "App\\Entity\\MedicalRecord" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'medicalRecord' => 'App\\Entity\\MedicalRecord',
        ]);
    }
}
