<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QG4ObYVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QG4ObYV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QG4ObYV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'medsRepository' => ['privates', 'App\\Repository\\MedsRepository', 'getMedsRepositoryService', true],
            'prescription' => ['privates', '.errored..service_locator.QG4ObYV.App\\Entity\\Prescription', NULL, 'Cannot autowire service ".service_locator.QG4ObYV": it references class "App\\Entity\\Prescription" but no such service exists.'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'mailer' => '?',
            'medsRepository' => 'App\\Repository\\MedsRepository',
            'prescription' => 'App\\Entity\\Prescription',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
