<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VCoDV9nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vCoDV9n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vCoDV9n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'streamRepository' => ['privates', 'App\\Repository\\StreamRepository', 'getStreamRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.vCoDV9n.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.vCoDV9n": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'streamRepository' => 'App\\Repository\\StreamRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
