<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6vvfYJPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6vvfYJP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6vvfYJP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medicalRecord' => ['privates', '.errored..service_locator.6vvfYJP.App\\Entity\\MedicalRecord', NULL, 'Cannot autowire service ".service_locator.6vvfYJP": it references class "App\\Entity\\MedicalRecord" but no such service exists.'],
        ], [
            'medicalRecord' => 'App\\Entity\\MedicalRecord',
        ]);
    }
}
