<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBilan2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xrMFbQ0.App\Entity\Bilan' shared service.
     *
     * @return \App\Entity\Bilan
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.xrMFbQ0": it references class "App\\Entity\\Bilan" but no such service exists.');
    }
}
