<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getComments2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yWsY15h.App\Entity\Comments' shared service.
     *
     * @return \App\Entity\Comments
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.yWsY15h": it references class "App\\Entity\\Comments" but no such service exists.');
    }
}
