<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMercure_Hub_Default_Publisher_Traceable_InnerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mercure.hub.default.publisher.traceable.inner' shared service.
     *
     * @return \Symfony\Component\Mercure\Publisher
     *
     * @deprecated Since symfony/mercure-bundle 0.2: The "mercure.hub.default.publisher.traceable.inner" service is deprecated. You should stop using it, as it will be removed in the future, use "mercure.hub.default" instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('symfony/mercure-bundle', '0.2', 'The "mercure.hub.default.publisher.traceable.inner" service is deprecated. You should stop using it, as it will be removed in the future, use "mercure.hub.default" instead.');

        return new \Symfony\Component\Mercure\Publisher($container->getEnv('MERCURE_URL'), ($container->privates['mercure.hub.default.jwt.provider'] ?? $container->getMercure_Hub_Default_Jwt_ProviderService()), ($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()));
    }
}
