<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedicalRecordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6vvfYJP.App\Entity\MedicalRecord' shared service.
     *
     * @return \App\Entity\MedicalRecord
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6vvfYJP": it references class "App\\Entity\\MedicalRecord" but no such service exists.');
    }
}
