<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMeds2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.vPQmH2E.App\Entity\Meds' shared service.
     *
     * @return \App\Entity\Meds
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.vPQmH2E": it references class "App\\Entity\\Meds" but no such service exists.');
    }
}
