<?php

namespace ContainerSqyrms2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebSocketServerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\WebSocketServerCommand' shared autowired service.
     *
     * @return \App\Command\WebSocketServerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'WebSocketServerCommand.php';

        $container->privates['App\\Command\\WebSocketServerCommand'] = $instance = new \App\Command\WebSocketServerCommand(($container->privates['App\\WebSocketServer'] ?? $container->load('getWebSocketServerService')));

        $instance->setName('app:websocket-server');

        return $instance;
    }
}
