<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Qf1hj2XService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Qf1hj2X' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Qf1hj2X'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mercureHub' => ['privates', 'mercure.hub.default.traceable', 'getMercure_Hub_Default_TraceableService', false],
            'streamRepository' => ['privates', 'App\\Repository\\StreamRepository', 'getStreamRepositoryService', true],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
            'user' => ['privates', '.errored..service_locator.Qf1hj2X.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.Qf1hj2X": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'mercureHub' => '?',
            'streamRepository' => 'App\\Repository\\StreamRepository',
            'urlGenerator' => '?',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
