<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q8IEr16Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q8IEr16' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q8IEr16'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'streamRepository' => ['privates', 'App\\Repository\\StreamRepository', 'getStreamRepositoryService', true],
        ], [
            'entityManager' => '?',
            'streamRepository' => 'App\\Repository\\StreamRepository',
        ]);
    }
}
