<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6OdyaQCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6OdyaQC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6OdyaQC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blog' => ['privates', '.errored..service_locator.6OdyaQC.App\\Entity\\Blog', NULL, 'Cannot autowire service ".service_locator.6OdyaQC": it references class "App\\Entity\\Blog" but no such service exists.'],
        ], [
            'blog' => 'App\\Entity\\Blog',
        ]);
    }
}
