<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T57PQDVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T57PQDV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T57PQDV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'webSocketServer' => ['privates', 'App\\WebSocketServer', 'getWebSocketServerService', true],
        ], [
            'entityManager' => '?',
            'webSocketServer' => 'App\\WebSocketServer',
        ]);
    }
}
