<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XqfuUljService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XqfuUlj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XqfuUlj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'prescription' => ['privates', '.errored..service_locator.XqfuUlj.App\\Entity\\Prescription', NULL, 'Cannot autowire service ".service_locator.XqfuUlj": it references class "App\\Entity\\Prescription" but no such service exists.'],
        ], [
            'prescription' => 'App\\Entity\\Prescription',
        ]);
    }
}
