<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E_5B9OyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E.5B9Oy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E.5B9Oy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medsRepository' => ['privates', 'App\\Repository\\MedsRepository', 'getMedsRepositoryService', true],
        ], [
            'medsRepository' => 'App\\Repository\\MedsRepository',
        ]);
    }
}
