<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GriU129Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.griU129' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.griU129'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medsRepository' => ['privates', 'App\\Repository\\MedsRepository', 'getMedsRepositoryService', true],
            'prescription' => ['privates', '.errored..service_locator.griU129.App\\Entity\\Prescription', NULL, 'Cannot autowire service ".service_locator.griU129": it references class "App\\Entity\\Prescription" but no such service exists.'],
        ], [
            'medsRepository' => 'App\\Repository\\MedsRepository',
            'prescription' => 'App\\Entity\\Prescription',
        ]);
    }
}
