<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VPQmH2EService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vPQmH2E' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vPQmH2E'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'med' => ['privates', '.errored..service_locator.vPQmH2E.App\\Entity\\Meds', NULL, 'Cannot autowire service ".service_locator.vPQmH2E": it references class "App\\Entity\\Meds" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'med' => 'App\\Entity\\Meds',
        ]);
    }
}
