<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JTMVvDwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jTMVvDw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jTMVvDw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'diagnosticRequest' => ['privates', '.errored..service_locator.jTMVvDw.App\\Entity\\DiagnosticRequest', NULL, 'Cannot autowire service ".service_locator.jTMVvDw": it references class "App\\Entity\\DiagnosticRequest" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'diagnosticRequest' => 'App\\Entity\\DiagnosticRequest',
            'entityManager' => '?',
        ]);
    }
}
