<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_81ah_BUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.81ah.bU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.81ah.bU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bilan' => ['privates', '.errored..service_locator.81ah.bU.App\\Entity\\Bilan', NULL, 'Cannot autowire service ".service_locator.81ah.bU": it references class "App\\Entity\\Bilan" but no such service exists.'],
        ], [
            'bilan' => 'App\\Entity\\Bilan',
        ]);
    }
}
