<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HGW_PulService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HGW.pul' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HGW.pul'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reclamationRepository' => ['privates', 'App\\Repository\\DiagnosticRequestRepository', 'getDiagnosticRequestRepositoryService', true],
        ], [
            'reclamationRepository' => 'App\\Repository\\DiagnosticRequestRepository',
        ]);
    }
}
