<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EaQOPUVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EaQOPUV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EaQOPUV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bilanRepository' => ['privates', 'App\\Repository\\BilanRepository', 'getBilanRepositoryService', true],
        ], [
            'bilanRepository' => 'App\\Repository\\BilanRepository',
        ]);
    }
}
