<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YWsY15hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yWsY15h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yWsY15h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'comment' => ['privates', '.errored..service_locator.yWsY15h.App\\Entity\\Comments', NULL, 'Cannot autowire service ".service_locator.yWsY15h": it references class "App\\Entity\\Comments" but no such service exists.'],
        ], [
            'comment' => 'App\\Entity\\Comments',
        ]);
    }
}
