<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XrMFbQ0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xrMFbQ0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xrMFbQ0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bilan' => ['privates', '.errored..service_locator.xrMFbQ0.App\\Entity\\Bilan', NULL, 'Cannot autowire service ".service_locator.xrMFbQ0": it references class "App\\Entity\\Bilan" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'bilan' => 'App\\Entity\\Bilan',
            'entityManager' => '?',
        ]);
    }
}
