<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDiagnosticRequest2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jTMVvDw.App\Entity\DiagnosticRequest' shared service.
     *
     * @return \App\Entity\DiagnosticRequest
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.jTMVvDw": it references class "App\\Entity\\DiagnosticRequest" but no such service exists.');
    }
}
