<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMercure_Hub_Default_Publisher_TraceableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mercure.hub.default.publisher.traceable' shared service.
     *
     * @return \Symfony\Component\Mercure\Debug\TraceablePublisher
     *
     * @deprecated Since symfony/mercure-bundle 0.2: The "mercure.hub.default.publisher.traceable" service is deprecated. Use "mercure.hub.default.traceable" instead.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('symfony/mercure-bundle', '0.2', 'The "mercure.hub.default.publisher.traceable" service is deprecated. Use "mercure.hub.default.traceable" instead.');

        return new \Symfony\Component\Mercure\Debug\TraceablePublisher($container->load('getMercure_Hub_Default_Publisher_Traceable_InnerService'), ($container->privates['debug.stopwatch'] ?? ($container->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
    }
}
