<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPrescriptionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.QG4ObYV.App\Entity\Prescription' shared service.
     *
     * @return \App\Entity\Prescription
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.QG4ObYV": it references class "App\\Entity\\Prescription" but no such service exists.');
    }
}
