<?php

namespace ContainerGf3SA4B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebSocketServerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\WebSocketServer' shared autowired service.
     *
     * @return \App\WebSocketServer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'cboden'.\DIRECTORY_SEPARATOR.'ratchet'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Ratchet'.\DIRECTORY_SEPARATOR.'ComponentInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'cboden'.\DIRECTORY_SEPARATOR.'ratchet'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Ratchet'.\DIRECTORY_SEPARATOR.'MessageInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'cboden'.\DIRECTORY_SEPARATOR.'ratchet'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Ratchet'.\DIRECTORY_SEPARATOR.'MessageComponentInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'WebSocketServer.php';

        return $container->privates['App\\WebSocketServer'] = new \App\WebSocketServer($container->load('getMercure_Hub_Default_Publisher_TraceableService'));
    }
}
