<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DiagnosticRequest extends \App\Entity\DiagnosticRequest implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'analyseType', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'creationDate', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'status', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'doctorNotes', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'type', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'radioType', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'diagnosticBilans', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'id_patient'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'id', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'analyseType', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'creationDate', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'status', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'doctorNotes', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'type', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'radioType', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'diagnosticBilans', '' . "\0" . 'App\\Entity\\DiagnosticRequest' . "\0" . 'id_patient'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DiagnosticRequest $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAnalyseType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnalyseType', []);

        return parent::getAnalyseType();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnalyseType(string $analyseType): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnalyseType', [$analyseType]);

        return parent::setAnalyseType($analyseType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreationDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreationDate', []);

        return parent::getCreationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreationDate(\DateTimeInterface $creationDate): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreationDate', [$creationDate]);

        return parent::setCreationDate($creationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoctorNotes(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoctorNotes', []);

        return parent::getDoctorNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoctorNotes(?string $doctorNotes): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoctorNotes', [$doctorNotes]);

        return parent::setDoctorNotes($doctorNotes);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getRadioType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRadioType', []);

        return parent::getRadioType();
    }

    /**
     * {@inheritDoc}
     */
    public function setRadioType(?string $radioType): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRadioType', [$radioType]);

        return parent::setRadioType($radioType);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiagnosticBilans(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiagnosticBilans', []);

        return parent::getDiagnosticBilans();
    }

    /**
     * {@inheritDoc}
     */
    public function addDiagnosticBilan(\App\Entity\Bilan $bilan): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDiagnosticBilan', [$bilan]);

        return parent::addDiagnosticBilan($bilan);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDiagnosticBilan(\App\Entity\Bilan $bilan): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDiagnosticBilan', [$bilan]);

        return parent::removeDiagnosticBilan($bilan);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdPatient(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdPatient', []);

        return parent::getIdPatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdPatient(?\App\Entity\User $id_patient): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdPatient', [$id_patient]);

        return parent::setIdPatient($id_patient);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserName', []);

        return parent::getUserName();
    }

}
