<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSqyrms2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSqyrms2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSqyrms2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSqyrms2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSqyrms2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sqyrms2',
    'container.build_id' => '77d2c544',
    'container.build_time' => 1715522194,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSqyrms2');
